source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LwScanningByZxing_Example', :exclusive => true do
  pod "LwScanningByZxing", :path => "../"
end

target 'LwScanningByZxing_Tests', :exclusive => true do
  pod "LwScanningByZxing", :path => "../"

  pod 'FBSnapshotTestCase'
end
